#!/usr/bin/env python3
"""Launcher for the espeak speaker node (installed to bin/ and lib/<pkg>/)."""
import sys

from espeak_speaker.espeak_node import main

if __name__ == '__main__':
    sys.exit(main())
